export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'

export const REQUEST_GOODS_PENDING = 'REQUEST_GOODS_PENDING';
export const REQUEST_GOODS_SUCCESS = 'REQUEST_GOODS_SUCCESS';
export const REQUEST_GOODS_FAILED = 'REQUEST_GOODS_FAILED';

export const LOAD_USER = 'LOAD_USER';

export const SET_ROUTE = 'SET_ROUTE';
export const ADMIN_SIGN_IN = 'ADMIN_SIGN_IN';